# Generated by Django 5.0 on 2023-12-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.SlugField()),
                ('summup', models.CharField(max_length=100)),
                ('article', models.TextField()),
                ('article_banner', models.ImageField(upload_to='article_images/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='date last modified')),
            ],
        ),
    ]
