# Generated by Django 5.0 on 2023-12-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='First article', max_length=50),
            preserve_default=False,
        ),
    ]
