# Generated by Django 5.0 on 2023-12-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_name',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
