# Generated by Django 5.0 on 2023-12-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_id_alter_post_slug_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='article_banner',
            new_name='banner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='article',
            new_name='text',
        ),
    ]
